<?php

return [
  'bank_list' => [
    "Agriculture Development Bank",
    "Nepal Bank",
    "Rastriya Banijya Bank",
    "Citizens Bank International Limited",
    "Everest Bank",
    "Global IME Bank Limited",
    "Himalayan Bank",
    "Kumari Bank",
    "Laxmi Sunrise Bank",
    "Machhapuchhre Bank",
    "Nabil Bank",
    "Nepal Investment Mega Bank",
    "Nepal SBI Bank",
    "NIC Asia Bank",
    "NMB Bank",
    "Prabhu Bank",
    "Prime Commercial Bank",
    "Sanima Bank",
    "Siddhartha Bank",
    "Standard Chartered Bank",
    "Corporate Development Bank",
    "Excel Development Bank",
    "Garima Bikas Bank",
    "Green Development Bank",
    "Jyoti Bikas Bank",
    "Kamana Sewa Bikas Bank",
    "Karnali Development Bank",
    "Lumbini Bikas Bank",
    "Mahalaxmi Development Bank",
    "Miteri Development Bank",
    "Muktinath Bikash Bank",
    "Narayani Development Bank",
    "Salapa Bikash Bank",
    "Saptakoshi Development Bank",
    "Sangrila Development Bank",
    "Shine Resunga Development Bank",
    "Sindhu Bikas Bank",
    "Best Finance",
    "Capital Merchant Banking & Finance",
    "Central Finance",
    "Gurkhas Finance",
    "Goodwill Finance",
    "Guheshwori Merchant Banking & Finance",
    "ICFC Finance",
    "Janaki Finance",
    "Manjushree Finance",
    "Multipurpose Finance",
    "Nepal Finance",
    "Nepal Share Markets & Finance",
    "Pokhara Finance",
    "Progressive Finance",
    "Reliance Finance",
    "Samriddhi Finance Company",
    "Shree Investment & Finance"
  ],
  'districts' => [
    "Achham",
    "Arghakhanchi",
    "Baglung",
    "Baitadi",
    "Bajhang",
    "Bajura",
    "Banke",
    "Bara",
    "Bardiya",
    "Bhaktapur",
    "Bhojpur",
    "Chitwan",
    "Dadeldhura",
    "Dailekh",
    "Dang",
    "Darchula",
    "Dhading",
    "Dhankuta",
    "Dhanusa",
    "Dolakha",
    "Dolpa",
    "Doti",
    "Eastern Rukum",
    "Gorkha",
    "Gulmi",
    "Humla",
    "Ilam",
    "Jajarkot",
    "Jhapa",
    "Jumla",
    "Kailali",
    "Kalikot",
    "Kanchanpur",
    "Kapilvastu",
    "Kaski",
    "Kathmandu",
    "Kavrepalanchok",
    "Khotang",
    "Lalitpur",
    "Lamjung",
    "Mahottari",
    "Makwanpur",
    "Manang",
    "Morang",
    "Mugu",
    "Mustang",
    "Myagdi",
    "Nawalpur",
    "Nuwakot",
    "Okhaldhunga",
    "Palpa",
    "Panchthar",
    "Parbat",
    "Parsa",
    "Pyuthan",
    "Ramechhap",
    "Rasuwa",
    "Rautahat",
    "Rolpa",
    "Rukum",
    "Rupandehi",
    "Salyan",
    "Sankhuwasabha",
    "Saptari",
    "Sarlahi",
    "Sindhuli",
    "Sindhupalchok",
    "Siraha",
    "Solukhumbu",
    "Sunsari",
    "Surkhet",
    "Syangja",
    "Tanahu",
    "Taplejung",
    "Terhathum",
    "Udayapur",
    "Western Rukum",
  ],
  'provinces' => [
    "Koshi",
    "Madhesh",
    "Bagmati",
    "Gandaki",
    "Lumbini",
    "Karnali",
    "Sudurpaschim",
  ],
  'occupation' => [
    'Business',
    'Agriculture',
    'Retired',
    'Student',
    'Housewife',
    'Government',
    'Expert',
    'Private',
    'Public',
    'Service',
    'Others',
  ],
  'designation_list' => [
    'Director',
    'Executive',
    'Shareholder',
    'Employee',
    'Others',
  ]
];

